### PR TITLE
Update roughViz and add pie charts

### PR DESCRIPTION
**Pull request by slang25**
I've added pie charts support for roughViz. While doing this I found that roughViz has had quite a few bugs fixed over the last year or so, but the new npm packages still contain the old minified bundle, I've raised an issue, but this repo looks dead.

I've switched over to a recently active version that works really well (I've abandoned my own fork).

### CODE REVIEW

**Comment by slang25** [comment]
image

**Comment by Zaid-Ajaj** [comment]
Awesome stuff @slang25 thanks a lot for the PR and for the goodies :smile:

If the fork is working well, then I don't mind using it. 

The code and docs look great, I will be able to run/test the code locally sometime tomorrow of over the weekend. 

If I don't encounter any issue, I will just merge and publish 💯

**Comment by Zaid-Ajaj** [comment]
@slang25 I have merged and tested (yes, in that order) your PR and everythings works great! Published v1.5 of the Feliz.RoughViz package which includes pie chart support 🚀 thanks again, really appreciate it 😄

**Comment by slang25** [comment]
Fantastic @Zaid-Ajaj I now get to delete some code! 🚀

**Pull request merged**
