### PR TITLE
Add ARIA props

### LINKED ISSUE #41: Add ARIA props
ARIA props should be added, e.g. `aria-labelledby`, `aria-describedby`, `aria-label`, etc.

The properties are listed [here](https://www.w3.org/WAI/PF/aria-1.1/states_and_properties) (e.g. section 6.6).

I know basically nothing about these, just enough to know they are crucial to accessibility.

### PR DESCRIPTION
**Pull request by cmeeren**
Closes #41

WIP, some props are yet to be added.

### CODE REVIEW

**Comment by cmeeren** [comment]
Please have a look at the overloads I have created and see if you think they're OK. There are a few `StringEnum`s, and some props are combinations of normal and "enum" props.

**Comment by Zaid-Ajaj** [comment]
Looks good to me! thanks a lot for this :heart:

**Comment by Zaid-Ajaj** [comment]
Whenever you are ready, I will merge and publish :)

**Comment by cmeeren** [comment]
Ready 👍

**Comment by Zaid-Ajaj** [comment]
Published as of v0.47 thanks a lot!

**Comment by cmeeren** [comment]
Happy to help!

**Pull request merged**
