### PR TITLE
Move UseListener to separate project

### PR DESCRIPTION
**Pull request by panmona**
I propose that we adopt https://github.com/Shmew/Feliz.UseListener into this project as this is already used in the Feliz docs.and to make it possible to use it with Fable 4. Currently there's a version restriction on the package:
image

I don't think that we'll be able to update the library on Shmew's account, I made a PR nonetheless. https://github.com/Shmew/Feliz.UseListener/pull/4

This would also need some additional build changes, so that the publishing works correctly. Not sure if this would already be done with just adding the new project name [here](https://github.com/Zaid-Ajaj/Feliz/blob/master/build/Program.fs) or if there's more to it.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello @panmona,

If your goal is to move ownership of Feliz.UseListener, it is better to ask the original maintainer first about it.

This is because he is the one who should give his consent for that and gives access to the package on NuGet. Indeed, you can't publish to a package that you don't own on NuGet.

**Comment by panmona** [comment]
What I would propose is to publish it under a different name just like with Feliz.Elmish/Feliz.UseElmish, as I'm aware that it isn't possible to publish under the same name. The original author didn't have any sign of activity in the last 2 years.

**Comment by MangelMaxime** [comment]
@panmona I am not sure what yo speaking about Feliz.Elmish doesn't exist.

If you are speaking about Fable.Elmish, then there are 2 packages because they solve different problem.

Let's wait to see if @Shmew is going to answer because you PR is only 1 day old. Or try to contact it via other channel like slack, discord, etc.

We can then decide what to do depending on the situation.

**Comment by panmona** [comment]
@MangelMaxime Sounds good.
I was referencing to this section in #535, maybe the text is wrong?
image

**Comment by MangelMaxime** [comment]
Not what they are speaking about because there are no `Feliz.Elmish` that I can see listed on [Nuget.org](https://www.nuget.org/packages?q=Feliz.Elmish).

But that's not really important :)

**Comment by Zaid-Ajaj** [comment]
@panmona I think this is a good idea. UseListener is a nice library and I was using it in Feliz.Router, it was a bummer that i couldn't use it for v4 of Feliz.Router and had to roll out my own helpers. 

I will have to look at the actual implementation code later. As for the name, something like `Feliz.Listeners` could do, don't really have a strong opinion on the matter

**Comment by Zaid-Ajaj** [comment]
Merged and published under a new name `Feliz.Listeners` with the same implementation :rocket:

**Comment by panmona** [comment]
Thank you!

**Pull request merged**
