### PR TITLE
Added overloads for onChange

### PR DESCRIPTION
**Pull request by TWith2Sugars**
I needed to grab an int and float from an html input element with a type of "number" and created two overloads to grab the value directly.

Is this something useful for others?

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Hi there @TWith2Sugars these overloads look useful but I don't want them to break once the input elements change their types to something other than `number`/`range` etc. Maybe you could change the implementation such that it only calls the handler when the `!!ev.target?value` is an instance of `Number`? this way `onChange` won't fire if is not a number

thoughts? 🤔

**Comment by Zaid-Ajaj** [comment]
There is actually a downside to this if onChange won't fire unless `type=number` although it makes sense, it might be a confusing to users who only changed the input type but not their handler that accepts `int` or `float`

**Comment by Zaid-Ajaj** [comment]
@TWith2Sugars Sorry I didn't get what you mean by "create an new input model with a number type" 🤔 I think checking for the runtime type should be good enough: i.e. testing with `typeof`
```fs
// into the Interop module maybe?
[<Emit "typeof $0 === 'number'">]
let isTypeofNumber (x: obj) : bool = jsNative

// onChange
Interop.mkAttr "onChange" (fun (ev: Event) -> 
    if Interop.isTypeofNumber (!!ev.target?value)  
    then handler (!!ev.target?value)
) 
```
What do you think?

**Comment by TWith2Sugars** [comment]
Yeah that would be simpler.

I was thinking along the lines of:

`
module prop =
    module input =
        [<Erase>]
        type number =
            static member inline onChange (handler: int -> unit) = Interop.mkAttr "onChange" (fun (ev: Event) -> handler (!!ev.target?value))
            static member inline onChange (handler: float -> unit) = Interop.mkAttr "onChange" (fun (ev: Event) -> handler (!!ev.target?value))
`

So the usage would be

`
Html.input[
    prop.`type`.number
    prop.input.number.onChange(fun _ -> ())
]
`

**Comment by Zaid-Ajaj** [comment]
Yeah let's not do that, it looks inconsistent with what the other `onChange` handlers are doing. Checking that the runtime type is a number should be enough. (though for `int -> unit` handlers it might give weird results unless we do `ceiling` on the value)

**Comment by TWith2Sugars** [comment]
I'll make the change as soon as I can. Want me to stick the isTypeofNumber in to interop then?

**Comment by Zaid-Ajaj** [comment]
> Want me to stick the isTypeofNumber in to interop then?

@TWith2Sugars yes please!

**Comment by TWith2Sugars** [comment]
I've made those changes btw :)

**Comment by Zaid-Ajaj** [comment]
@TWith2Sugars  Awesome! thanks a lot! I will try to merge and publish a new version as soon as possible

**Comment by Zaid-Ajaj** [comment]
Published as of v1.46 🚀

**Pull request merged**
